// Generated by CIRCT firtool-1.128.0
module pieceInfoEntry(
  input       clock,
  input       reset,
  input       establish,
  input [8:0] establishEntry_byteId,
  input [2:0] establishEntry_nfId,
  input [2:0] establishEntry_pieceWidth
);

  wire [8:0] establishEntry_byteId_0 = establishEntry_byteId;
  wire [2:0] establishEntry_nfId_0 = establishEntry_nfId;
  wire [2:0] establishEntry_pieceWidth_0 = establishEntry_pieceWidth;
  reg  [8:0] pieceInfo_Q_byteId;
  reg  [2:0] pieceInfo_Q_nfId;
  reg  [2:0] pieceInfo_Q_pieceWidth;
  always @(posedge clock) begin
    if (establish)
      pieceInfo_Q_byteId <= establishEntry_byteId_0;
    else begin
    end
  end // always @(posedge)
  always @(posedge clock) begin
    if (establish)
      pieceInfo_Q_nfId <= establishEntry_nfId_0;
    else begin
    end
  end // always @(posedge)
  always @(posedge clock) begin
    if (establish)
      pieceInfo_Q_pieceWidth <= establishEntry_pieceWidth_0;
    else begin
    end
  end // always @(posedge)
endmodule

